<?php
/**
 * @file
 * Firefox OS favicon creation.
 */

/**
 * Implements hook_favicon_generator_admin().
 */
function favicon_generator_firefox_favicon_generator_admin() {
  $form = array();
  $form['favicon_generator_firefox'] = array(
    '#type' => 'select',
    '#title' => t('Firefox OS Style'),
    '#options' => array(
      'circle' => t('Circle'),
      'rsquare' => t('Rounded Square'),
      'square' => t('Square'),
    ),
    '#default_value' => variable_get('favicon_generator_firefox', 'circle'),
  );
  $form['favicon_generator_firefox_incircle'] = array(
    '#type' => 'checkbox',
    '#title' => t('Keep picture in circle'),
    '#description' => t('If checked, the icon is cropped in order to fit the circle. Else, the icon may extend beyond the circle.'),
    '#default_value' => variable_get('favicon_generator_firefox_incircle', 1),
    '#states' => array(
      'visible' => array(
        ':input[name="favicon_generator_firefox"]' => array('value' => 'circle'),
      ),
    ),
  );

  return $form;
}

/**
 * Implements hook_favicon_generator_spec().
 */
function favicon_generator_firefox_favicon_generator_spec($settings) {
  $array = array('firefox_app' => array());
  $ff = variable_get('favicon_generator_firefox', 'circle');
  if ($ff == 'circle') {
    $array['firefox_app'] = array(
      'picture_aspect' => 'circle',
      'keep_picture_in_circle' => 'true',
      'circle_inner_margin' => $settings['margin'],
      'margin' => $settings['margin'],
      'background_color' => $settings['color'],
      'keep_picture_in_circle' => variable_get('favicon_generator_firefox_incircle', 1) == 1 ? 'true' : 'false',
    );
  }
  elseif ($ff == 'rsquare') {
    $array['firefox_app'] = array(
      'picture_aspect' => 'rounded_square',
      'margin' => $settings['margin'],
      'background_color' => $settings['color'],
    );
  }
  elseif ($ff == 'square') {
    $array['firefox_app'] = array(
      'picture_aspect' => 'square',
      'margin' => $settings['margin'],
      'background_color' => $settings['color'],
    );
  }

  return $array;
}
